### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Sudopia** [Ysgorg/canvas-lms-downloader#2]
I have not used npm before but when I tried to run the npm ci command to presumably install the program, my terminal output this error. Maybe this is an easy fix? Thanks.
-----------------------------

npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-11-05T19_57_24_659Z-debug.log

------------- Debug log pasted below ----------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'ci' ]
2 info using npm@6.14.7
3 info using node@v14.10.0
4 verbose npm-session 0e37d1b3fbbae8ef
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /home/username/Documents/nmt course backup utility/canvas-lms-downloader
8 verbose checkLock verifying package-lock data
9 verbose teardown shutting down workers.
10 info teardown Done in 0s
11 verbose stack Error: cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
11 verbose stack     at Installer.checkLock (/usr/lib/node_modules/npm/node_modules/libcipm/index.js:165:9)
11 verbose stack     at /usr/lib/node_modules/npm/node_modules/libcipm/index.js:139:16
12 verbose cwd /home/username/Documents/nmt course backup utility/canvas-lms-downloader
13 verbose Linux 4.19.144-1-MANJARO
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci"
15 verbose node v14.10.0
16 verbose npm  v6.14.7
17 error cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
18 verbose exit [ 1, true ]

----------npm version--------
running "npm -v" shows that my npm version is 6.14.7

**Comment by Ysgorg** [comment]
Looks like I made a switch to a different package manager (`yarn`) but didn't update the docs. I changed back to `npm` now. Thanks for reporting, should be fixed now.

**Comment by Sudopia** [comment]
Hey, that is some quick customer service. Install successful, thanks stranger. Hopefully I can download all (or most) of my canvas course with your software. A different repo I tried looked very well featured but seemed to use a different API access method than me. All I am able to generate is an "access token". 

On another note, I am somewhat surprised that github does not have a messaging feature built in.
